---
title: "Documentation And More Details About The Data"
subtitle: "How AMLO's MORENA Took Over Mexican Politics"
date: "Sep 17, 2024"
author: "Kevin Valdivia"
format: html
toc: false # Table of contents
execute: 
  warning: false
  message: false
---

### Latinobarometro

# Codebook for Latinobarómetro Data

| Variable Name                  | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|---------------------|---------------------------------------------------|
| `JudiciaryIndependence`        | *Por favor, dígame si está muy de acuerdo (1), de acuerdo (2), en desacuerdo (3) o muy en desacuerdo (4), con las siguientes afirmaciones. El poder judicial debe ser independiente del ejecutivo.* <br> **English:** Please tell me if you strongly agree (1), agree (2), disagree (3), or strongly disagree (4) with the following statements. The judiciary should be independent of the executive.                                                                                                      |
| `MediaControlPresident`        | *Por favor, dígame si está muy de acuerdo (1), de acuerdo (2), en desacuerdo (3) o muy en desacuerdo (4), con las siguientes afirmaciones. En caso de dificultades está bien que el presidente controle los medios de comunicación.* <br> **English:** Please tell me if you strongly agree (1), agree (2), disagree (3), or strongly disagree (4) with the following statements. In case of difficulties, it's okay for the president to control the media.                                                |
| `SupportForMilitaryGovernment` | *Apoyaría un gobierno militar si las cosas se ponen muy difíciles.* <br> **English:** Would you support a military government if things get very difficult?                                                                                                                                                                                                                                                                                                                                                 |
| `PresidentialApproval`         | *¿Ud. aprueba o no aprueba la gestión del gobierno que encabeza el presidente (nombre)?* <br> **English:** Do you approve or disapprove of the management of the government led by the president (name)?                                                                                                                                                                                                                                                                                                    |
| `PoliticalSelfPositioning`     | *En política, la gente normalmente habla de “izquierda” y “derecha”. En una escala donde 0 es la izquierda y 10 es la derecha, ¿dónde te ubicarías?* <br> **English:** In politics, people usually talk about “left” and “right.” On a scale where 0 is left and 10 is right, where would you place yourself?                                                                                                                                                                                               |
| `CongressTrust`                | *Por favor, mire esta tarjeta y dígame, para cada uno de los grupos, instituciones o personas de la lista ¿cuánta confianza tiene usted en ellas: mucha (1), algo (2), poca (3) o ninguna confianza (4) en...? Congreso* <br> **English:** Please look at this card and tell me, for each of the groups, institutions, or people on the list, how much trust you have in them: a lot (1), some (2), little (3), or no trust (4) in...? Congress.                                                            |
| `JudiciaryTrust`               | *Por favor, mire esta tarjeta y dígame, para cada uno de los grupos, instituciones o personas de la lista ¿cuánta confianza tiene usted en ellas: mucha (1), algo (2), poca (3) o ninguna confianza (4) en...? Poder Judicial* <br> **English:** Please look at this card and tell me, for each of the groups, institutions, or people on the list, how much trust you have in them: a lot (1), some (2), little (3), or no trust (4) in...? Judiciary.                                                     |
| `PresidentialTrust`            | *Por favor, mire esta tarjeta y dígame, para cada uno de los grupos, instituciones o personas de la lista ¿cuánta confianza tiene usted en ellas: mucha (1), algo (2), poca (3) o ninguna confianza (4) en...? El presidente* <br> **English:** Please look at this card and tell me, for each of the groups, institutions, or people on the list, how much trust you have in them: a lot (1), some (2), little (3), or no trust (4) in...? The president.                                                  |
| `ElectoralInstitutionTrust`    | *Por favor, mire esta tarjeta y dígame, para cada uno de los grupos, instituciones o personas de la lista ¿cuánta confianza tiene usted en ellas: mucha (1), algo (2), poca (3) o ninguna confianza (4) en...? {la institución Electoral del país}* <br> **English:** Please look at this card and tell me, for each of the groups, institutions, or people on the list, how much trust you have in them: a lot (1), some (2), little (3), or no trust (4) in...? The electoral institution of the country. |
| `PoliticalPartiesTrust`        | *Por favor, mire esta tarjeta y dígame, para cada uno de los grupos, instituciones o personas de la lista ¿cuánta confianza tiene usted en ellas: mucha (1), algo (2), poca (3) o ninguna confianza (4) en...? Los partidos políticos* <br> **English:** Please look at this card and tell me, for each of the groups, institutions, or people on the list, how much trust you have in them: a lot (1), some (2), little (3), or no trust (4) in...? Political parties.                                     |
| `GovernanceByPowerGroups`      | *En términos generales ¿Diría usted que {PAÍS} está gobernado por unos cuantos grupos poderosos en su propio beneficio, o que está gobernado para el bien de todo el pueblo?* <br> **English:** In general, would you say that {COUNTRY} is governed by a few powerful groups for their own benefit, or that it is governed for the good of all the people?                                                                                                                                                 |
